plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
    id 'maven-publish'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.java
            }
        }
    }
}

group = 'net.bewis09.renderite'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

kotlin {
    jvmToolchain(20)
}

test {
    useJUnitPlatform()
}